(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "color-moccur")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "gitignore-mode")
(depends-on "guide-key")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "leuven-theme")
(depends-on "magit")
(depends-on "memoize")
(depends-on "moccur-edit" :git "https://github.com/myuhe/moccur-edit.el.git")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "request")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "tango-plus-theme")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
;;;pallet-ignore
